### ISSUE TITLE
[vite] Internal server error: Unterminated template when generating source map

### ISSUE THREAD

**Issue by fourdim** [iFaxity/vite-plugin-istanbul#133]
### Describe the bug

When there is a `class` inside it, it will raise the error.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ctjuqx?file=main.ts

### System Info

```shell
System:
    OS: Linux 6.4 Arch Linux
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 19.27 GB / 23.44 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.config/nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.config/nvm/versions/node/v18.16.1/bin/npm
    pnpm: 8.6.12 - ~/.config/nvm/versions/node/v18.16.1/bin/pnpm
  Browsers:
    Chromium: 116.0.5845.96
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4 
    vite: ^4.3.9 => 4.4.9 
    vite-plugin-istanbul: ^5.0.0 => 5.0.0
```

### Used Package Manager

pnpm

### Logs

<details>
<summary>[vite] Internal server error: Unterminated template</summary>

```shell
3:08:54 AM [vite] Internal server error: Unterminated template
  Plugin: vite:istanbul
  File: masked/packages/blocks/src/database-block/kanban/cell.ts
      at Espree.raise (file://masked/node_modules/.pnpm/espree@9.6.1/node_modules/espree/lib/espree.js:263:25)
      at pp.readTmplToken (file://masked/node_modules/.pnpm/acorn@8.10.0/node_modules/acorn/dist/acorn.mjs:5710:47)
      at pp.tryReadTemplateToken (file://masked/node_modules/.pnpm/acorn@8.10.0/node_modules/acorn/dist/acorn.mjs:5687:10)
      at types.q_tmpl [as override] (file://masked/node_modules/.pnpm/acorn@8.10.0/node_modules/acorn/dist/acorn.mjs:2277:67)
      at pp.nextToken (file://masked/node_modules/.pnpm/acorn@8.10.0/node_modules/acorn/dist/acorn.mjs:5166:48)
      at pp.next (file://masked/node_modules/.pnpm/acorn@8.10.0/node_modules/acorn/dist/acorn.mjs:5128:8)
      at Espree.tokenize (file://masked/node_modules/.pnpm/espree@9.6.1/node_modules/espree/lib/espree.js:143:22)
      at Module.tokenize (file://masked/node_modules/.pnpm/espree@9.6.1/node_modules/espree/espree.js:120:38)
      at createIdentitySourceMap (file://masked/node_modules/.pnpm/vite-plugin-istanbul@5.0.0_vite@4.4.9/node_modules/vite-plugin-istanbul/dist/index.mjs:3153:25)
      at TransformContext.transform (file://masked/node_modules/.pnpm/vite-plugin-istanbul@5.0.0_vite@4.4.9/node_modules/vite-plugin-istanbul/dist/index.mjs:3276:53)
      at Object.transform (file://masked/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.11/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file://masked/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.11/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file://masked/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.11/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
```
</details>

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/iFaxity/vite-plugin-istanbul/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/iFaxity/vite-plugin-istanbul/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a vite-plugin-istanbul issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iFaxity** [comment]
Hi @fourdim,

The issue is related to a dependency (espree).
I suggest you file an issue in that repository since it has nothing to do with this plugin directly.

Thanks!
